# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:12
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('link', models.URLField(max_length=255, unique=True, verbose_name='Link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Data da publicaçâo')),
                ('enclosure', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL do podcast')),
                ('to_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON')),
            ],
            options={
                'db_table': 'episode',
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nome')),
                ('feed', models.CharField(max_length=255, unique=True, verbose_name='Feed')),
                ('image', models.TextField(blank=True, default='/static/dist/img/podcast-banner.png', null=True, verbose_name='Banner')),
                ('total_episodes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de Episódios')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'podcast',
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='PodcastLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(default='pt', max_length=20, null=True, verbose_name='Código')),
                ('name', models.CharField(default='português', max_length=60, null=True, verbose_name='Nome')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'podcast_language',
                'verbose_name': 'Idioma do podcast',
                'verbose_name_plural': 'Idiomas dos podcasts',
            },
        ),
        migrations.CreateModel(
            name='PopularTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('term', models.CharField(max_length=255, verbose_name='Termo')),
                ('times', models.IntegerField(default=1, verbose_name='Numero de vezes')),
                ('date_search', models.DateField(blank=True, default=datetime.datetime(2017, 6, 28, 22, 12, 26, 800754), null=True, verbose_name='Data da busca')),
            ],
            options={
                'ordering': ['date_search'],
                'db_table': 'popular_term',
                'verbose_name': 'Termo popular',
                'verbose_name_plural': 'Termos populares',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'db_table': 'tag',
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TopicSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_recorded', models.BooleanField(verbose_name='Já foi gravado?')),
            ],
            options={
                'db_table': 'topic_suggestion',
                'verbose_name': 'Sugestão de Tema',
                'verbose_name_plural': 'Sugestões de Temas',
            },
        ),
        migrations.AddIndex(
            model_name='topicsuggestion',
            index=models.Index(fields=['title'], name='ix_topic_suggestion_title'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='ix_tag_name'),
        ),
        migrations.AddIndex(
            model_name='popularterm',
            index=models.Index(fields=['term'], name='ix_popular_term_term'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PodcastLanguage', verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Podcast', verbose_name='Podcast'),
        ),
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=models.ManyToManyField(db_table='tags', to='api.Tag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['name'], name='ix_podcast_name'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['feed'], name='ix_podcast_feed'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['link'], name='ix_episode_link'),
        ),
    ]
