# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='podcastlanguage',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='popularterm',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='topicsuggestion',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='popularterm',
            name='date_search',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 22, 23, 51, 37, 955820), null=True),
        ),
    ]
